### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by JJbroome** [RickyVanz/Obscure-Armory#2]
there is an error with the MTs255
here is the before and after for that bit of code

before
{
    "id": "mts255",
	"type": "GUN",
	"name": "MTs255",
	"description": "Russian-made shotgun with 5-shell internal revolving cylinder, combining revolver mechanism with shotgun apparently is a good combo for russians. it also has picattiny rail for sight device.",
	"weight": "3700 g",
	"volume": "1870 ml",
	"price": 4000000,
	"to_hit": -1,
	"bashing": 15,
	"material": [ "wood", "steel", ].
	"symbol": "(",
	"color": "dark_gray",
	"ammo": "shot",
	"skill": "shotgun",
	"range": 20,
	"ranged_damage": 5,
	"recoil": 110,
	"dispersion": 120,
	"durability": 8,
	"loudness": 15,
	"clip_size": 5,
	"reload": 100,
	"flags": [ "RELOAD_ONE", "NEVER_JAMS" ]
  }

after
{
    "id": "mts255",
	"type": "GUN",
	"name": "MTs255",
	"description": "Russian-made shotgun with 5-shell internal revolving cylinder, combining revolver mechanism with shotgun apparently is a good combo for russians. it also has picattiny rail for sight device.",
	"weight": "3700 g",
	"volume": "1870 ml",
	"price": 4000000,
	"to_hit": -1,
	"bashing": 15,
	"material": [ "wood", "steel" ],
	"symbol": "(",
	"color": "dark_gray",
	"ammo": "shot",
	"skill": "shotgun",
	"range": 20,
	"ranged_damage": 5,
	"recoil": 110,
	"dispersion": 120,
	"durability": 8,
	"loudness": 15,
	"clip_size": 5,
	"reload": 100,
	"flags": [ "RELOAD_ONE", "NEVER_JAMS" ]
  }

**Comment by RickyVanz** [comment]
ahh slipped one comma there in material.. sorry for late reply.

HOTFIX incoming.

**Comment by RickyVanz** [comment]
HOTFIX applied.. let me know if there is anything wrong.

**Comment by JJbroome** [comment]
I'll test some more when I get home, but everything seems fine so far
